#!/bin/sh

if [ $# -lt 2 ]; then
	echo "Usage: $0 ZNC_USER ZNC_PASS"
	exit 1
fi

ZNC_USER=$1
# FIXME: password will be visible in process list. Read it from stdin?
ZNC_PASS=$2

mkdir -p .znc/configs
openssl req -subj '/CN=znc.docker/O=ZNC Docker./C=US' -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout /.znc/server.key -out /.znc/server.crt
cat /.znc/server.key > /.znc/znc.pem && cat /.znc/server.crt >> /.znc/znc.pem
# FIXME: call znc --makepass instead of generating the has manually
ZNC_SALT="$(dd if=/dev/urandom bs=16c count=1 | md5sum | awk '{print $1}')"
ZNC_HASH="sha256#$(echo -n ${ZNC_PASS}${ZNC_SALT} | sha256sum | awk '{print $1}')#$ZNC_SALT#"
cat >.znc/configs/znc.conf <<EOF

LoadModule = lastseen
<Listener l>
        Port = 6667
        IPv4 = true
        IPv6 = true
        SSL = true
</Listener>

<User $ZNC_USER>
        Pass       = $ZNC_HASH
        Admin      = true
        Nick       = $ZNC_USER
        AltNick    = _$ZNC_USER
        Ident      = $ZNC_USER
        RealName   = $ZNC_USER
        Buffer     = 200
        KeepBuffer = false
        ChanModes  = +stn
	MaxJoins   = 1

        LoadModule = admin
        LoadModule = keepnick
        LoadModule = kickrejoin
        LoadModule = nickserv
        LoadModule = simple_away

        Server     = irc.freenode.net 6667
</User>
EOF
exec znc -r -f -d /.znc
